version: '2'

services:
  modpoll:
    build: .
    container_name: modpoll
    command: modpoll --tcp modsim.topmaker.net --config https://raw.githubusercontent.com/gavinying/modpoll/master/examples/modsim.csv
